# Test against this version of Node.js
environment:
  nodejs_version: "12.13.1"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Upgrade npm
  - npm install -g npm@6
  # install modules
  - npm install
  - npm install grunt-cli -g
  - npm install mocha -g

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
